name: fix code styling

on:
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      php:
        description: 'Php version'
        default: "8.1"
        type: string
      message:
        description: 'Commit message'
        default: Fix code styling
        type: string

jobs:
  laravel-pint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.message }}
