name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ retry-* ]

jobs:
  laravel-tests-and-deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: test types syntax
      run: |
        exit 1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --force
    - name: Install NPM dependencies
      run: npm install
    - name: Minify CSS and JS files
      run: npm run production
    # - name: Execute tests (Unit and Feature tests) via PHPUnit
    #   env:
    #     DB_CONNECTION: sqlite
    #     DB_DATABASE: database/database.sqlite
    #   run: ./vendor/bin/phpunit

    # - name: Deploy
    #   run: |
    #     mkdir -p ~/.ssh
    #     touch ~/.ssh/key.pem
    #     (echo ${{ secrets.PRIVATE_KEY }} | base64 --decode -i > ~/.ssh/key.pem)
    #     chmod 700 ~/.ssh/key.pem
    #     cd ../.deploy
    #     php ./deployer.phar deploy

    - name: Deploy on stupid hosting
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        debug: true
        script: |
          cd ~/public_html
          git checkout -f
          git pull
          cd src/
          composer install --optimize-autoloader --no-dev
          php artisan optimize

    # err: bash: line 4: composer: command not found
    # добавить удаление архивов, которые оставляет "appleboy/scp-action"

    - name: Sleep for 21 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '21s'

    - name: Upload frontend js & css on hosting
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "src/public/js/*,src/public/css/*,src/public/mix-manifest.json"
        target: "~/public_html"

    - name: Send success status
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Success deploying ✅



  ##################################
  ### Run when a schedule failed ###
  ##################################
  restart_when_failed:
    name: Restarts workflow if failed
    runs-on: ubuntu-latest
    if: failure() # && ${{ github.event.client_payload.attempt < secrets.DEPLOY_MAX_ATTEMPTS }} # set var !!!!
    needs: laravel-tests-and-deploy
    steps:
      - name: Sleep for 1m 36s
        uses: jakejarvis/wait-action@master
        with:
          time: '96s'

      - name: set attempt
        run: |
          ATTEMPT=${{ github.event.client_payload.attempt }}
          ATTEMPT=$([ -n "$ATTEMPT" ] && echo $((++ATTEMPT)) || echo 1)
          echo "attempt=1" >> $GITHUB_ENV

      - name: Send retry status
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Failure deploy (${{ env.attempt }}) ❌ Rerun 🔄

      - name: Retry the workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.API_WORKFLOW_KEY }}
          event-type: retry-${{ env.attempt }}
          client-payload: '{"ref": "${{ github.ref }}", "attempt": "${{ env.attempt }}"}'
