name: PHPStan

on: [ push, pull_request_target ]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Copy .env
        run: php -r "file_exists('src/.env') || copy('src/.env.example', 'src/.env');"

      - name: Download and extract sxGeo database
        run: |
          wget https://sypexgeo.net/files/SxGeoCountry.zip
          unzip SxGeoCountry.zip -d src/database/sxgeo

      - name: Install dependencies
        working-directory: ./src
        run: composer install --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute PHPStan
        run: src/vendor/bin/phpstan analyse
