name: PHPStan

on: [ push, pull_request ]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Install dependencies
        working-directory: ./src
        run: composer install --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute PHPStan
        run: src/vendor/bin/phpstan analyse
