name: Production-rollback

on: workflow_dispatch

concurrency: production_environment

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Rollback
      uses: deployphp/action@v1
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      with:
        private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        dep: rollback

    - name: Send success status
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Rollback - done ↩️
